format files and add format script
thirdweb-dev/portal pull request #77
Opened 2022-04-14 10:44 UTC by avneesh0612

The files weren't formatted and there was no script for formatting them so added the prettier one. We can also add this in pre commit

2022-04-14 11:50 UTC, nachoiacovino requested changes
can you use this prettier config?

{
  "singleQuote": false,
  "trailingComma": "all",
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
}

2022-04-14 11:58 UTC, avneesh0612 commented
Adding 
```"importOrderSeparation": true,
"importOrderSortSpecifiers": true```
would just give this warning- [warn] Ignored unknown option { importOrderSeparation: true, importOrderSortSpecifiers: true }.

2022-04-18 19:55 UTC, nachoiacovino requested changes

2022-04-18 19:55 UTC, nachoiacovino commented on portal/guides/sell-nft-multiple-currencies.mdx
> +---
why is this in this branch? :D

2022-04-19 01:11 UTC, avneesh0612 commented on portal/guides/sell-nft-multiple-currencies.mdx
> +---
Oh rip lmao

2022-04-19 15:41 UTC, closed without merging