add 'Sell your NFT in multiple currencies at the same time' guide
thirdweb-dev/portal pull request #79
Opened 2022-04-14 12:48 UTC by avneesh0612

2022-04-18 20:02 UTC, nachoiacovino requested changes
mostly small things!

2022-04-18 20:02 UTC, nachoiacovino commented on portal/guides/sell-nft-multiple-currencies.mdx
> +date: "2022-04-15"
```suggestion
date: "2022-04-19"
```

2022-04-18 20:02 UTC, nachoiacovino commented on portal/guides/sell-nft-multiple-currencies.mdx
> +If you are also going to use the [template](https://github.com/thirdweb-example/next-typescript-starter) then follow these steps-
```suggestion
If you are also going to use the [Next TypeScript template](https://github.com/thirdweb-example/next-typescript-starter) then follow these steps
```

Don't use the dashes at the end of the sentences, use colons ":"

2022-04-18 20:02 UTC, nachoiacovino commented on portal/guides/sell-nft-multiple-currencies.mdx
> +- Install the dependencies-
```suggestion
- Install the dependencies:
```

2022-04-18 20:02 UTC, nachoiacovino commented on portal/guides/sell-nft-multiple-currencies.mdx
> +```tsx
```suggestion
```tsx:index.tsx
```

Add the whole index.tsx file here

2022-04-18 20:02 UTC, nachoiacovino commented on portal/guides/sell-nft-multiple-currencies.mdx
> +Instead of showing the disconnect Wallet button and wallet address we will now show the card instead. So, replace everything inside the fragment with the following-
```suggestion
Instead of showing the disconnect Wallet button and wallet address we will now show the card instead. So, replace everything inside the fragment with the following-
```

Can you clarify what a fragment is?

2022-04-18 20:02 UTC, nachoiacovino commented on portal/guides/sell-nft-multiple-currencies.mdx
> +You might be wondering that where are we getting the nft object, we are going to create a new file and store the nft object there to keep our code clean. So, create a new file `nft.ts` and add this-
```suggestion
You might be wondering where are we getting the NFT object, we are going to create a new file and store the NFT object there to keep our code clean. So, create a new file `nft.ts` and add this-
```

Capitalize NFT on text always, also fix typo

2022-04-18 20:02 UTC, nachoiacovino commented on portal/guides/sell-nft-multiple-currencies.mdx
> +```
```suggestion
```jsx
```

needs language type

2022-04-18 20:02 UTC, nachoiacovino commented on portal/guides/sell-nft-multiple-currencies.mdx
> +```ts
```suggestion
```ts:api/generate-mint-sig.ts
```

Add file names (with folders)

2022-04-18 20:02 UTC, nachoiacovino commented on portal/guides/sell-nft-multiple-currencies.mdx
> +```ts
to all code snippets in which you're showing substantial code or you're changing from file to file

2022-04-19 01:12 UTC, avneesh0612 commented on portal/guides/sell-nft-multiple-currencies.mdx
> +Instead of showing the disconnect Wallet button and wallet address we will now show the card instead. So, replace everything inside the fragment with the following-
Sure

2022-04-19 13:48 UTC, nachoiacovino commented
awesome!

2022-04-19 13:48 UTC, merged